language: php

php:
  - 5.4
  - 5.3

env:
  - REF=" " # latest
  - REF="master"
  - REF="5.7.0-wip"

before_script:
    - composer install
    - echo 'short_open_tag = On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - git clone https://github.com/concrete5/concrete5.git
    - cd concrete5
    - git checkout `git describe --abbrev=0 --tags` # checkout latest tag
    - git checkout $REF
    - cd ..
    - mv concrete5/web web
    - mysql -e 'CREATE DATABASE concrete5_tests;'
    - vendor/bin/install-concrete5.php --db-server=localhost --db-username=travis --db-database=concrete5_tests --admin-email=webmaster@example.org --admin-password=password --target=../../../web

script: phpunit --testsuite all_helpers

matrix:
  allow_failures:
    - env: REF="5.7.0-wip"
